site_name: 'Structure_threader manual'
#site_favicon: 'assets/Icon.png'
pages:
    - 'Introduction': 'index.md'
    - 'Installation & dependencies': 'install.md'
    - 'External programs': 'external.md'
    - 'Usage': 'usage.md'
    - 'Output': 'output.md'
    - 'Test Data': 'test_data.md'
    - 'Benchmarking': 'benckmark.md'
    - 'Citation': 'citation.md'
    - 'Future Plans': 'future.md'
    - 'FAQ': 'faq.md'
